"""add extension_instances

Revision ID: 859afd3e27a1
Revises: 8949947d9621
Create Date: 2026-03-28 16:29:22.863725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859afd3e27a1'
down_revision: Union[str, Sequence[str], None] = '8949947d9621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instance_token', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('os_name', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_token')
    )
    op.create_index(op.f('ix_extension_instances_last_seen'), 'extension_instances', ['last_seen'], unique=False)
    op.create_index(op.f('ix_extension_instances_user_id'), 'extension_instances', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extension_instances_user_id'), table_name='extension_instances')
    op.drop_index(op.f('ix_extension_instances_last_seen'), table_name='extension_instances')
    op.drop_table('extension_instances')
    # ### end Alembic commands ###
